name=Pervasive_BWRY_Small
version=10.1.1
author=Pervasive Displays Inc.
maintainer=Arvin Tan <https://www.pervasivedisplays.com/>
sentence=Driver for Pervasive Displays colour screens 
paragraph=black-white-red-yellow, small size
category=Display
url=https://github.com/PervasiveDisplays
architectures=*
depends=PDLS_Common (>=10.1.1)
